name: Java CI

on:
  push:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew --no-daemon build
    - name: Archive protogram test results
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: protogram-report
        path: protogram/build/reports/tests/allTests
    - name: Archive tinsel test results
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: tinsel-report
        path: tinsel/build/reports/tests/allTests
    - name: Archive test test results
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: test-report
        path: test/build/reports/tests/allTests
    - name: Archive cli test results
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: cli-report
        path: cli/build/reports/tests/test
