name: Publish to brew

on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Gradle
      run: ./gradlew --no-daemon build

    - name: Get version
      id: get_version
      run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
    
    - name: Set SHA
      id: shasum
      run: |
        echo ::set-output name=sha::"$(shasum -a 256 cli/build/bin/protogram | awk '{printf $1}')"
        
    - name: Extract release notes
      id: release_notes
      uses: ffurrer2/extract-release-notes@v1

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        body: ${{ steps.release_notes.outputs.release_notes }}
        prerelease: false
        files: cli/build/bin/protogram
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Bump Brew
      env: 
        HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.BREW_TOKEN }}
      run: |
        brew tap mattprecious/repo
        brew bump-formula-pr -f --version=${{ steps.get_version.outputs.version }} --no-browse --no-audit \
        --sha256=${{ steps.shasum.outputs.sha }} \
        --url="https://github.com/mattprecious/protogram/releases/download/${{ steps.get_version.outputs.version }}/protogram" \
        mattprecious/repo/protogram
